<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zmb</string>
		<string>zm</string>
		<string>zb</string>
		<string>zl</string>
		<string>zlang</string>
	</array>
	<key>name</key>
	<string>Zoomba Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.zoomba</string>
		</dict>
		<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.zoomba</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.source.zoomba</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([+-])?\d+(\.)?\d*\b|\btrue\b|\bfalse\b|\bnull\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnew\b|\bif\b|\belse\b|\bwhile\b|\bwhere\b|\bfor\b|\breturn\b|\bbreak\b|\bcontinue\b|;|\bas\b|\bimport\b|\bdef\b|\bisa\b|\bdel\b|\bswitch\b|\bcase\b</string>
			<key>name</key>
			<string>keyword.control.zoomba</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@ARGS|\$[\.a-zA-Z0-9\$]*|@\$</string>
			<key>name</key>
			<string>support.variable.zoomba</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\^|\||\+|\-|%|\*|\/|\=|\(|\)|\{|\}|\[|\]|\:|&amp;|&lt;|&gt;|~|!|@|\$|\?|#\^|#\$</string>
			<key>name</key>
			<string>keyword.operator.zoomba</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b#clock\b|\b#atomic\b|\b#retry\b|\bqueue\b|\btimeout\b|\bsystem\b|\btask\b|\bbatch\b|\beprintf\b|\beprintln\b|\basync\b|\bfrom\b|\bselect\b|\blist\b|\bslist\b|\bset\b|\bsset\b|\bdict\b|\bsdict\b|\bpartition\b|\bfold\b|\blfold\b|\brfold\b|\bfind\b|\bindex\b|\brindex\b|\bexists\b|\bmset\b|\bopen\b|\bpopen\b|\bfile\b|\bfiber\b|\bxml\b|\bxpath\b|\bxelem\b|\bjson\b|\byaml\b|\bsign\b|\bread\b|\bwrite\b|\bbool\b|\bchar\b|\bint\b|\bfloat\b|\bFLOAT\b|\bINT\b|\bpanic\b|\bsize\b|\bempty\b|\bprintln\b|\bprintf\b|\bproxy\b|\bthread\b|\btype\b|\bround\b|\bfloor\b|\bceil\b|\bassert\b|\brandom\b|\breduce\b|\brreduce\b|\bsum\b|\bminmax\b|\bmatrix\b|\bnum\b|\benum\b|\btest\b|\bbye\b|\bdb\b|\bload\b|\bsorta\b|\bsortd\b|\bshuffle\b|\bjoin\b|\bstr\b|\bjstr\b|\bystr\b|\bheap\b|\bis\b|\btime\b|\btokens\b|\bseq\b|\bperm\b|\bcomb\b|\bpowerset\b|\buniq\b|\boset\b|\bodict\b|\btuple\b|\bhash\b|\bpoll\b|\blog\b|\bgroup\b|#</string>
			<key>name</key>
			<string>support.function.zoomba</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(_|_/|#)?"(?:[^"\\]|\\.)*"</string>
			<key>name</key>
			<string>string.double_quoted.zoomba</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(_|_/|#)?'(?:[^'\\]|\\.)*'</string>
			<key>name</key>
			<string>string.single_quoted.zoomba</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.zoomba</string>
	<key>uuid</key>
	<string>81606576-92f4-11e6-ae22-56b6b6499611</string>
</dict>
</plist>
